name: Node.js Continuous Integration

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Setup node environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install needed dependencies    
      run: npm ci
      working-directory: ./server
    - name: Build Typescript files 
      run: npm run build
      working-directory: ./server
    - name: Start express server 
      run: npm start &
      working-directory: ./server
    - name: Run back-end testing suite
      run: npm test
      working-directory: ./server
      
